### ISSUE TITLE
gencert remote argument doesn't honor is_ca in config.json

### ISSUE THREAD

**Issue by ronlipke** [cloudflare/cfssl#621] opened 2016-06-24 01:32 UTC
We're seeing an issue when generating intermediate CA certs with `gencert` and the `-remote` argument.  It doesn't seem to honor the `is_ca` line in config.json.  If we remove the remote endpoint and run `gencert` with the `-ca` and `-ca-key` switch it works fine and sets the correct Basic Constraints.

Is this intentional?  Is there a method to generating intermediate CA certs without requiring a local copy of the root's cert and key?

**Comment by lziest** [comment] 2016-06-24 18:59
I am working on a PR to fix that. Stay tuned :)

**Comment by lziest** [comment] 2016-07-07 14:49
PR #626 solves half of the issue, which is to let root CA, the remote signer, control the issued intermediate CA's pathlen constraints. But the CA owner like you would need to draft the signing profile for the remote signer. 
The other half of the issue is that when issue a cert with remote signer, many controls in local `config.json` is invalid, this requires better documentation. The `is_ca` line for example at local `config.json` will be ignored. After all, it is the remote signer who decides how to issue a certificate, so it is remote signer's `config.json` taking effect.

**Comment by lziest** [comment] 2016-07-19 18:43
Pull requests are merged, @ronlipke do you think your issue is resolved?

**Comment by lziest** [comment] 2016-07-19 18:44
Now `cfssl` will warn about ignored signing config as well.

**Comment by ronlipke** [comment] 2016-07-19 18:46
I honestly haven't had a chance to go back and test, but I'll try and get to it shortly and let you know.

Thanks for looking at this!

**Comment by kisom** [comment] 2016-09-21 00:55
Should be closed by #626.

**Closed by kisom** 2016-09-21 00:55 UTC
Labels: bug
